-- Daybook's tables on the shared kaze-master-in project (ADR-0002).
--
-- Table names are unqualified on purpose: Supabase applies this with the
-- default search_path (public), and the test harness applies the very same
-- file into a throwaway schema (src/server/testing/testDb.ts).
--
-- RLS is enabled with NO policies: the anon/authenticated Data API roles can
-- read nothing. Only the Hono server, connecting as the database owner via
-- DATABASE_URL, touches these tables — access is gated by the family PIN.

CREATE TABLE daybook_workers (
  id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                  text    NOT NULL,
  role                  text,                          -- optional label, e.g. 'Maid'
  joined_on             date    NOT NULL,
  archived_on           date,
  paid_leaves_per_cycle integer NOT NULL DEFAULT 2
);

CREATE TABLE daybook_rate_periods (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id      integer NOT NULL REFERENCES daybook_workers(id),
  rate_rupees    integer NOT NULL,
  effective_from date    NOT NULL                      -- first row = joined_on
);
CREATE INDEX daybook_rate_periods_worker_id_idx ON daybook_rate_periods (worker_id);

CREATE TABLE daybook_cycle_configs (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id      integer NOT NULL REFERENCES daybook_workers(id),
  start_day      integer NOT NULL CHECK (start_day BETWEEN 1 AND 28),
  effective_from date    NOT NULL                      -- first row = joined_on
);
CREATE INDEX daybook_cycle_configs_worker_id_idx ON daybook_cycle_configs (worker_id);

CREATE TABLE daybook_marks (
  worker_id integer NOT NULL REFERENCES daybook_workers(id),
  date      date    NOT NULL,
  state     text    NOT NULL CHECK (state IN ('leave', 'off')),
  PRIMARY KEY (worker_id, date)                        -- present = no row
);

CREATE TABLE daybook_payments (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id     integer NOT NULL REFERENCES daybook_workers(id),
  period_start  date    NOT NULL,
  period_end    date    NOT NULL,
  amount_rupees integer NOT NULL,
  paid_on       date    NOT NULL,
  UNIQUE (worker_id, period_start, period_end)         -- one Payment per Worker-Cycle
);

CREATE TABLE daybook_settings (
  key   text PRIMARY KEY,                              -- pin_hash, session_secret
  value text NOT NULL
);

ALTER TABLE daybook_workers       ENABLE ROW LEVEL SECURITY;
ALTER TABLE daybook_rate_periods  ENABLE ROW LEVEL SECURITY;
ALTER TABLE daybook_cycle_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE daybook_marks         ENABLE ROW LEVEL SECURITY;
ALTER TABLE daybook_payments      ENABLE ROW LEVEL SECURITY;
ALTER TABLE daybook_settings      ENABLE ROW LEVEL SECURITY;
